-- PM Checklist Templates Seed Data
-- Generated from factory CSV checklist files
-- Machine IDs: DT-2, TU-1, SC-2

-- Clear existing templates for these machines (optional)
DELETE FROM pm_checklist_templates WHERE machine_id IN ('DT-2', 'TU-1', 'SC-2');

INSERT INTO pm_checklist_templates (machine_id, list_type, equipment_no, equipment_name, part_name, essential_care, sort_order)
VALUES
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Adaptors', 'Check cond.&change if required', 1),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Drive pin', 'Check cond.&change if required', 2),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Bobbin brake disk', 'Check cond.', 3),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Bobbin brake pads', 'Check cond.&change if required', 4),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Fork brake disk', 'Check cond.', 5),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Fork brake pads', 'Check cond.&change if required', 6),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Open/close pintels', 'Clean&grease', 7),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Open/close pintel lock', 'Check cond.&change if required', 8),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Open/close gear boxes', 'Check&grease', 9),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Open/close transmition movment', 'Check cond.&change if required', 10),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Hyd. Pump', 'Check cond.&repair if required', 11),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Oil level', 'Check oil level&add if required', 12),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Hyd.valves', 'Check cond.&change if required', 13),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Hyd.cylinders', 'Check cond.&change if required', 14),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Hyd.hoses', 'Check cond.&change if required', 15),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Platform balance', 'Check alignment', 16),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Fork centering lock', 'Check cond.', 17),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Main bearing', 'Grease', 18),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Timing belts', 'Check cond.&change if required', 19),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Chains', 'Check cond.&grease', 20),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Gear boxes oil', 'Check oil level&add oil if required', 21),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'loading trolley', 'Check movment', 22),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'V-belts', 'Check cond.&change if required', 23),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Air service unit', 'Lib&check cond.&change if required', 24),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Air cylinders', 'Lib&check cond.&change if required', 25),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Air valves', 'Lib&check cond.&change if required', 26),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Air hoses', 'Check cond.&change if required', 27),
  ('DT-2', 'mechanical', 1, 'PAY OFF', 'Air fitting', 'Check cond.&change if required', 28),
  ('DT-2', 'mechanical', 2, 'STEEL WIRE PAY OFF', 'Pulleys', 'Check (bearing,shaft,surface)', 29),
  ('DT-2', 'mechanical', 2, 'STEEL WIRE PAY OFF', 'Rollers', 'Check (bearing,shaft,surface)', 30),
  ('DT-2', 'mechanical', 2, 'STEEL WIRE PAY OFF', 'Guide ceramic', 'Check cond.&change if required', 31),
  ('DT-2', 'mechanical', 3, 'GUIDE ROLLERS', 'Guide rollers', 'Check (bearing,shaft,surface)', 32),
  ('DT-2', 'mechanical', 4, 'DIE HOLDER', 'Die clamp', 'Check cond.&change if required', 33),
  ('DT-2', 'mechanical', 4, 'DIE HOLDER', 'Forward/backwark', 'Grease shaft&guides', 34),
  ('DT-2', 'mechanical', 5, 'STEEL TAPING HEAD', 'Tape brake disk', 'Check cond.&repair if required', 35),
  ('DT-2', 'mechanical', 5, 'STEEL TAPING HEAD', 'Tape brake pads', 'Check cond.&change if required', 36),
  ('DT-2', 'mechanical', 5, 'STEEL TAPING HEAD', 'Cage brake disk', 'Check cond.&repair if required', 37),
  ('DT-2', 'mechanical', 5, 'STEEL TAPING HEAD', 'Cage brake pads', 'Check cond.&change if required', 38),
  ('DT-2', 'mechanical', 5, 'STEEL TAPING HEAD', 'Guide rollers', 'Check (bearing,shaft,surface)', 39),
  ('DT-2', 'mechanical', 5, 'STEEL TAPING HEAD', 'Main bearings', 'Check cond.&grease', 40),
  ('DT-2', 'mechanical', 5, 'STEEL TAPING HEAD', 'Shaft bearing', 'Check cond.&grease', 41),
  ('DT-2', 'mechanical', 5, 'STEEL TAPING HEAD', 'Gear box oil level', 'Check oil level&add if required', 42),
  ('DT-2', 'mechanical', 5, 'STEEL TAPING HEAD', 'Timing belt', 'Check cond.&change if required', 43),
  ('DT-2', 'mechanical', 5, 'STEEL TAPING HEAD', 'Air valves', 'Lib&check cond.&change if required', 44),
  ('DT-2', 'mechanical', 5, 'STEEL TAPING HEAD', 'Air hoses', 'Check cond.&change if required', 45),
  ('DT-2', 'mechanical', 5, 'STEEL TAPING HEAD', 'Air fitting', 'Check cond.&change if required', 46),
  ('DT-2', 'mechanical', 6, 'COUNTER METER', 'Pulley', 'Check (bearing,shaft,surface)', 47),
  ('DT-2', 'mechanical', 6, 'COUNTER METER', 'Timing belt', 'Check cond.&change if required', 48),
  ('DT-2', 'mechanical', 6, 'COUNTER METER', 'Guide rollers', 'Check (bearing,shaft,surface)', 49),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Gear boxes oil level', 'Check oil level&add if required', 50),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Brake disk', 'Check cond.&repair if required', 51),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Brake pads', 'Check cond.&change if required', 52),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Main bearing', 'Grease', 53),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Chains', 'Check cond.&grease', 54),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Drive belts', 'Check cond.&change if required', 55),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Tension cylinders', 'Check cond.&change if required', 56),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Tension pulleys', 'Check cond.&bearings', 57),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Drive pulleys', 'Check cond.&key way', 58),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Pressing cylinders', 'Check cond.&change if required', 59),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Pressing rollers', 'Check bearing stuck&change if required', 60),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Guide rollers', 'Check (bearing,shaft,surface)', 61),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Rotating shaft bearing', 'Grease', 62),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Coupling', 'Check cond.&change if required', 63),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Timing belt', 'Check cond.&change if required', 64),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Air service unit', 'Lib&check cond.&change if required', 65),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Air valves', 'Lib&check cond.&change if required', 66),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Air hoses', 'Check cond.&change if required', 67),
  ('DT-2', 'mechanical', 7, 'CATERPILLAR', 'Air fitting', 'Check cond.&change if required', 68),
  ('DT-2', 'mechanical', 8, 'GENERAL INSPECTION', 'Main shaft couplings', 'Check cond.', 69),
  ('DT-2', 'mechanical', 8, 'GENERAL INSPECTION', 'Main shaft bearings', 'Check cond.&change if required', 70),
  ('DT-2', 'mechanical', 8, 'GENERAL INSPECTION', 'Gear boxes oil', 'Check oil level&add if required', 71),
  ('DT-2', 'mechanical', 8, 'GENERAL INSPECTION', 'V- belts', 'Check cond.&change if required', 72),
  ('DT-2', 'mechanical', 8, 'GENERAL INSPECTION', 'V- pulleys', 'Check cond.&change if required', 73),
  ('DT-2', 'mechanical', 8, 'GENERAL INSPECTION', 'Timing belt', 'Check cond.&change if required', 74),
  ('DT-2', 'mechanical', 8, 'GENERAL INSPECTION', 'Timing pulleys', 'Check cond.&repair if required', 75),
  ('DT-2', 'mechanical', 8, 'GENERAL INSPECTION', 'Brake disk', 'Check cond.', 76),
  ('DT-2', 'mechanical', 8, 'GENERAL INSPECTION', 'Brake pads', 'Check cond.&change if required', 77),
  ('DT-2', 'mechanical', 8, 'GENERAL INSPECTION', 'Air valves', 'Lib&check cond.&change if required', 78),
  ('DT-2', 'mechanical', 8, 'GENERAL INSPECTION', 'Air hoses', 'Check cond.&change if required', 79),
  ('DT-2', 'mechanical', 8, 'GENERAL INSPECTION', 'Air fitting', 'Check cond.&change if required', 80),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Adaptors', 'Check cond.&change if required', 81),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Drive pin', 'Check cond.&change if required', 82),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Cage brake disk', 'Check cond.&repair if required', 83),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Cage brake pads', 'Check cond.&change if required', 84),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Open/close pintels', 'Clean&grease', 85),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Open/close pintel lock', 'Check cond.&change if required', 86),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Open/close gear boxes', 'Check&grease', 87),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Open/close transmition movment', 'Check cond.&change if required', 88),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Hyd. Pump', 'Check cond.&repair if required', 89),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Hyd.oil level', 'Check oil level&add if required', 90),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Hyd.valves', 'Check cond.&change if required', 91),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Hyd.cylinders', 'Check cond.&change if required', 92),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Hyd.hoses', 'Check cond.&change if required', 93),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Platform balance', 'Check alignment', 94),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Cage centering cylinder', 'Check cond.', 95),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Under rollers', 'Check cond.(surface&bearings)', 96),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Main bearing', 'Grease', 97),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Coupling', 'Check cond.&change if required', 98),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Chains', 'Check cond.&grease', 99),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Timing belt', 'Check cond.&change if required', 100),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Gear boxes oil level', 'Check oil level&add if required', 101),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'External gears', 'Check cond.&grease', 102),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Shaft bearing', 'Grease', 103),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Traverse rollers', 'Check cond.&change if required', 104),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Traverse shaft', 'Check cond.&grease', 105),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Traverse nut', 'Grease&check cond.&change if required', 106),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Traverse guide bars', 'Clean&grease', 107),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Air service unit', 'Lib&check cond.&change if required', 108),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Air valves', 'Lib&check cond.&change if required', 109),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Air hoses', 'Check cond.&change if required', 110),
  ('DT-2', 'mechanical', 9, 'TAKE UP', 'Air fitting', 'Check cond.&change if required', 111),
  ('DT-2', 'electrical', 1, 'PAY OFF', 'Open/close motor', 'Check cond.&clean by dry air', 1),
  ('DT-2', 'electrical', 1, 'PAY OFF', 'Hyd. Motors', 'Check cond.&clean by dry air', 2),
  ('DT-2', 'electrical', 1, 'PAY OFF', 'Cooling fan', 'Check cond.&clean by dry air', 3),
  ('DT-2', 'electrical', 1, 'PAY OFF', 'Limit switches', 'Check cond.&change if required', 4),
  ('DT-2', 'electrical', 1, 'PAY OFF', 'Carbon brushes', 'Check cond.&change if required', 5),
  ('DT-2', 'electrical', 1, 'PAY OFF', 'Slip rings', 'Check cond.&clean by dry air', 6),
  ('DT-2', 'electrical', 1, 'PAY OFF', 'Terminal boxes', 'Clean by dry air', 7),
  ('DT-2', 'electrical', 2, 'TAPING HEAD', 'Limit switches', 'Check cond.&change if required', 8),
  ('DT-2', 'electrical', 2, 'TAPING HEAD', 'Air pressure switch', 'Check cond.&change if required', 9),
  ('DT-2', 'electrical', 2, 'TAPING HEAD', 'Carbon brushes', 'Check cond.&change if required', 10),
  ('DT-2', 'electrical', 2, 'TAPING HEAD', 'Slip rings', 'Check cond.&clean by dry air', 11),
  ('DT-2', 'electrical', 2, 'TAPING HEAD', 'Terminal boxes', 'Clean by dry air', 12),
  ('DT-2', 'electrical', 3, 'COUNTER METER', 'Encoder', 'Check cond.&signal', 13),
  ('DT-2', 'electrical', 3, 'COUNTER METER', 'Sensors', 'Check cond.&signal', 14),
  ('DT-2', 'electrical', 4, 'CATERPILLAR', 'Limit switches', 'Check cond.&change if required', 15),
  ('DT-2', 'electrical', 4, 'CATERPILLAR', 'Tachometer', 'Check cond.&signal', 16),
  ('DT-2', 'electrical', 4, 'CATERPILLAR', 'Air pressure switch', 'Check cond.&change if required', 17),
  ('DT-2', 'electrical', 4, 'CATERPILLAR', 'Slip rings', 'Check cond.&clean by dry air', 18),
  ('DT-2', 'electrical', 4, 'CATERPILLAR', 'Carbon brushes', 'Check cond.&change if required', 19),
  ('DT-2', 'electrical', 4, 'CATERPILLAR', 'Terminal boxes', 'Clean by dry air', 20),
  ('DT-2', 'electrical', 5, 'GENERAL INSPECTION', 'Main motor', 'Check cond.&clean by dry air', 21),
  ('DT-2', 'electrical', 5, 'GENERAL INSPECTION', 'Cooling blower', 'Check cond.&clean by dry air', 22),
  ('DT-2', 'electrical', 5, 'GENERAL INSPECTION', 'Tachometer', 'Check cond.&signal', 23),
  ('DT-2', 'electrical', 5, 'GENERAL INSPECTION', 'Air pressure switch', 'Check cond.&change if required', 24),
  ('DT-2', 'electrical', 5, 'GENERAL INSPECTION', 'Limit switches', 'Check cond.&change if required', 25),
  ('DT-2', 'electrical', 5, 'GENERAL INSPECTION', 'Carbon brushes', 'Check cond.&change if required', 26),
  ('DT-2', 'electrical', 5, 'GENERAL INSPECTION', 'Slip rings', 'Check cond.&clean by dry air', 27),
  ('DT-2', 'electrical', 5, 'GENERAL INSPECTION', 'Terminal boxes', 'Clean by dry air', 28),
  ('DT-2', 'electrical', 6, 'TAKE UP', 'Reel motor', 'Check cond.&clean by dry air', 29),
  ('DT-2', 'electrical', 6, 'TAKE UP', 'Hyd. Motor', 'Check cond.&clean by dry air', 30),
  ('DT-2', 'electrical', 6, 'TAKE UP', 'Open/close motor', 'Check cond.&clean by dry air', 31),
  ('DT-2', 'electrical', 6, 'TAKE UP', 'Traverse motor', 'Check cond.&clean by dry air', 32),
  ('DT-2', 'electrical', 6, 'TAKE UP', 'Cooling fan', 'Check cond.&clean by dry air', 33),
  ('DT-2', 'electrical', 6, 'TAKE UP', 'Tachometer', 'Check cond.&signal', 34),
  ('DT-2', 'electrical', 6, 'TAKE UP', 'Sensors', 'Check cond.&change if required', 35),
  ('DT-2', 'electrical', 6, 'TAKE UP', 'Centering cylinder sensors', 'Check cond.&signal', 36),
  ('DT-2', 'electrical', 6, 'TAKE UP', 'Limit switches', 'Check cond.&change if required', 37),
  ('DT-2', 'electrical', 6, 'TAKE UP', 'Platform limit switches', 'Check cond.&change if required', 38),
  ('DT-2', 'electrical', 6, 'TAKE UP', 'Carbon brushes', 'Check cond.&change if required', 39),
  ('DT-2', 'electrical', 6, 'TAKE UP', 'Slip rings', 'Check cond.&clean by dry air', 40),
  ('DT-2', 'electrical', 6, 'TAKE UP', 'Air pressure switch', 'Check cond.&change if required', 41),
  ('DT-2', 'electrical', 6, 'TAKE UP', 'Terminal boxes', 'Clean by dry air', 42),
  ('DT-2', 'electrical', 7, 'CONTROL PANEL', 'Air condition', 'Clean by dry air', 43),
  ('DT-2', 'electrical', 7, 'CONTROL PANEL', 'Retight power cables', 'Retight cables', 44),
  ('DT-2', 'electrical', 7, 'CONTROL PANEL', 'Retight control cables', 'Arrange&retight loose wires', 45),
  ('DT-2', 'electrical', 7, 'CONTROL PANEL', 'All cct brakers & switches', 'Clean&check&change if required', 46),
  ('DT-2', 'electrical', 7, 'CONTROL PANEL', 'All transformers', 'Clean by dry air', 47),
  ('DT-2', 'electrical', 7, 'CONTROL PANEL', 'All fuses', 'Clean&check&change if required', 48),
  ('DT-2', 'electrical', 7, 'CONTROL PANEL', 'All contactors', 'Clean&check&change if required', 49),
  ('DT-2', 'electrical', 7, 'CONTROL PANEL', 'All relays', 'Clean&check&change if required', 50),
  ('DT-2', 'electrical', 7, 'CONTROL PANEL', 'All electronic components', 'Clean&check&change if required', 51),
  ('DT-2', 'electrical', 7, 'CONTROL PANEL', 'D.C.drive fuses&thyrstars', 'Clean&check&change if required', 52),
  ('DT-2', 'electrical', 7, 'CONTROL PANEL', 'Drive control', 'Clean&check', 53),
  ('DT-2', 'electrical', 7, 'CONTROL PANEL', 'All terminals', 'Clean&check', 54),
  ('DT-2', 'electrical', 7, 'CONTROL PANEL', 'Indication lamp', 'Clean&check&change if required', 55),
  ('DT-2', 'electrical', 7, 'CONTROL PANEL', 'Doors', 'Check all doors lock', 56),
  ('TU-1', 'mechanical', 1, 'PAY OFF', 'Adaptors', 'Check cond.&change if required', 1),
  ('TU-1', 'mechanical', 1, 'PAY OFF', 'Drive pin', 'Check cond.&change if required', 2),
  ('TU-1', 'mechanical', 1, 'PAY OFF', 'Brake disk', 'Check cond.&repair if required', 3),
  ('TU-1', 'mechanical', 1, 'PAY OFF', 'Brake pads', 'Check cond.&change if required', 4),
  ('TU-1', 'mechanical', 1, 'PAY OFF', 'Open/close shafts', 'Clean&grease', 5),
  ('TU-1', 'mechanical', 1, 'PAY OFF', 'Open/close nuts', 'Check cond.&change if required', 6),
  ('TU-1', 'mechanical', 1, 'PAY OFF', 'Open/close guide bars', 'Clean&grease', 7),
  ('TU-1', 'mechanical', 1, 'PAY OFF', 'Up/down shafts', 'Clean&grease', 8),
  ('TU-1', 'mechanical', 1, 'PAY OFF', 'Up/down nuts', 'Check cond.&change if required', 9),
  ('TU-1', 'mechanical', 1, 'PAY OFF', 'Up/down guide bars', 'Clean&grease', 10),
  ('TU-1', 'mechanical', 1, 'PAY OFF', 'Air pressure regulator', 'Lib&check cond.&change if required', 11),
  ('TU-1', 'mechanical', 1, 'PAY OFF', 'Air valves', 'Lib&check cond.&change if required', 12),
  ('TU-1', 'mechanical', 1, 'PAY OFF', 'Air hoses', 'Check cond.&change if required', 13),
  ('TU-1', 'mechanical', 1, 'PAY OFF', 'Air fitting', 'Check cond.&change if required', 14),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Bobbin adaptors', 'Check cond.&change if required', 15),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Bobbin drive pin', 'Check cond.&change if required', 16),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Bobbin brake disk', 'Check cond.&repair if required', 17),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Bobbin brake rope', 'Check cond.&change if required', 18),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Cage brake disk', 'Check cond.', 19),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Cage brake pads', 'Check cond.&change if required', 20),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Guide dies', 'Check cond.&change if required', 21),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Guide rollers', 'Check (bearing,shaft,surface)', 22),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Open/close pintels sys.', 'Check cond.&repair if required', 23),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'V-belts', 'Check cond.&change if required', 24),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'V-pulleys', 'Check cond.&change if required', 25),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Timing belts', 'Check cond.&change if required', 26),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Doors', 'Check cond.&repair if required', 27),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Gear boxes oil level', 'Check oil level&add if required', 28),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Main shaft couplings', 'Check cond.&retight if required', 29),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Main shaft bearings', 'Check cond.&grease', 30),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Oil level', 'Check oil level&add if required', 31),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Oil pump', 'Check cond.&clean by dry air', 32),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Oil hoses', 'Check cond.&change if required', 33),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Sight glass', 'Clean', 34),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Air service unit', 'Lib&check cond.&change if required', 35),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Air cylinders', 'Lib&check cond.&change if required', 36),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Air valves', 'Lib&check cond.&change if required', 37),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Air hoses', 'Check cond.&change if required', 38),
  ('TU-1', 'mechanical', 2, 'TUBULAR', 'Air fitting', 'Check cond.&change if required', 39),
  ('TU-1', 'mechanical', 3, 'CAPSTAN', 'Wheels', 'Check (bearing,shaft,surface)', 40),
  ('TU-1', 'mechanical', 3, 'CAPSTAN', 'Coupling', 'Check cond.&retight if required', 41),
  ('TU-1', 'mechanical', 3, 'CAPSTAN', 'Gear boxes oil level', 'Check oil level&add if required', 42),
  ('TU-1', 'mechanical', 3, 'CAPSTAN', 'Oil pump', 'Check cond.&clean by dry air', 43),
  ('TU-1', 'mechanical', 3, 'CAPSTAN', 'Oil hoses', 'Check cond.&change if required', 44),
  ('TU-1', 'mechanical', 3, 'CAPSTAN', 'Sight glass', 'Clean', 45),
  ('TU-1', 'mechanical', 4, 'TAKE UP', 'Adaptors', 'Check cond.&change if required', 46),
  ('TU-1', 'mechanical', 4, 'TAKE UP', 'Drive pin', 'Check cond.&change if required', 47),
  ('TU-1', 'mechanical', 4, 'TAKE UP', 'Gear boxes oil', 'Check oil level&add if required', 48),
  ('TU-1', 'mechanical', 4, 'TAKE UP', 'Open/close shafts', 'Clean&grease', 49),
  ('TU-1', 'mechanical', 4, 'TAKE UP', 'Open/close nuts', 'Check cond.&change if required', 50),
  ('TU-1', 'mechanical', 4, 'TAKE UP', 'Open/close guide bars', 'Clean&grease', 51),
  ('TU-1', 'mechanical', 4, 'TAKE UP', 'Up/down shafts', 'Clean&grease', 52),
  ('TU-1', 'mechanical', 4, 'TAKE UP', 'Up/down nuts', 'Check cond.&change if required', 53),
  ('TU-1', 'mechanical', 4, 'TAKE UP', 'Up/down guide bars', 'Clean&grease', 54),
  ('TU-1', 'mechanical', 4, 'TAKE UP', 'Traverse shafts', 'Clean&grease', 55),
  ('TU-1', 'mechanical', 4, 'TAKE UP', 'Traverse nuts', 'Check cond.&change if required', 56),
  ('TU-1', 'mechanical', 4, 'TAKE UP', 'Traverse guide bars', 'Clean&grease', 57),
  ('TU-1', 'mechanical', 4, 'TAKE UP', 'Chains', 'Check cond.&grease', 58),
  ('TU-1', 'mechanical', 4, 'TAKE UP', 'Guide rollers', 'Check (bearing,shaft,surface)', 59),
  ('TU-1', 'electrical', 1, 'PAY OFF', 'Open/close motor', 'Check cond.&clean by dry air', 1),
  ('TU-1', 'electrical', 1, 'PAY OFF', 'Open/close limit switch', 'Check cond.&change if required', 2),
  ('TU-1', 'electrical', 1, 'PAY OFF', 'Up/down motors', 'Clean by dry air', 3),
  ('TU-1', 'electrical', 1, 'PAY OFF', 'Up/down limit switches', 'Check cond.&change if required', 4),
  ('TU-1', 'electrical', 1, 'PAY OFF', 'Cooling fan', 'Check cond.&clean by dry air', 5),
  ('TU-1', 'electrical', 1, 'PAY OFF', 'Terminal boxes', 'Clean by dry air', 6),
  ('TU-1', 'electrical', 2, 'TABULAR', 'Main motor', 'Check cond.&clean by dry air', 7),
  ('TU-1', 'electrical', 2, 'TABULAR', 'Carbon brushes', 'Check cond.&change if required', 8),
  ('TU-1', 'electrical', 2, 'TABULAR', 'Slip rings', 'Check cond.&clean by dry air', 9),
  ('TU-1', 'electrical', 2, 'TABULAR', 'Cooling fan filter', 'Change filter', 10),
  ('TU-1', 'electrical', 2, 'TABULAR', 'Oil pump motor', 'Check cond.&clean by dry air', 11),
  ('TU-1', 'electrical', 2, 'TABULAR', 'Oil cooling motor', 'Check cond.&clean by dry air', 12),
  ('TU-1', 'electrical', 2, 'TABULAR', 'Limit switches', 'Check cond.&change if required', 13),
  ('TU-1', 'electrical', 2, 'TABULAR', 'Encoder', 'Check cond.&signal', 14),
  ('TU-1', 'electrical', 2, 'TABULAR', 'Sensors', 'Check cond.&signal', 15),
  ('TU-1', 'electrical', 2, 'TABULAR', 'Air pressure switch', 'Check cond.&change if required', 16),
  ('TU-1', 'electrical', 2, 'TABULAR', 'Lights', 'Check cond.&change if required', 17),
  ('TU-1', 'electrical', 2, 'TABULAR', 'Terminal boxes', 'Clean by dry air', 18),
  ('TU-1', 'electrical', 3, 'CAPSTAN', 'Sensors', 'Check cond.&signal', 19),
  ('TU-1', 'electrical', 3, 'CAPSTAN', 'Limit switches', 'Check cond.&change if required', 20),
  ('TU-1', 'electrical', 3, 'CAPSTAN', 'Terminal boxes', 'Clean by dry air', 21),
  ('TU-1', 'electrical', 4, 'TAKE UP', 'Open/close motor', 'Check cond.&clean by dry air', 22),
  ('TU-1', 'electrical', 4, 'TAKE UP', 'Open/close limit switch', 'Check cond.&change if required', 23),
  ('TU-1', 'electrical', 4, 'TAKE UP', 'Up/down motors', 'Clean by dry air', 24),
  ('TU-1', 'electrical', 4, 'TAKE UP', 'Up/down limit switches', 'Check cond.&change if required', 25),
  ('TU-1', 'electrical', 4, 'TAKE UP', 'Traverse motor', 'Check cond.&clean by dry air', 26),
  ('TU-1', 'electrical', 4, 'TAKE UP', 'Traverse limit switches', 'Check cond.&change if required', 27),
  ('TU-1', 'electrical', 4, 'TAKE UP', 'Winding motors', 'Check cond.&clean by dry air', 28),
  ('TU-1', 'electrical', 4, 'TAKE UP', 'Sensors', 'Check cond.&signal', 29),
  ('TU-1', 'electrical', 4, 'TAKE UP', 'Terminal boxes', 'Clean by dry air', 30),
  ('TU-1', 'electrical', 5, 'CONTROL PANEL', 'Air condition', 'Clean by dry air', 31),
  ('TU-1', 'electrical', 5, 'CONTROL PANEL', 'Retight power cables', 'Retight cables', 32),
  ('TU-1', 'electrical', 5, 'CONTROL PANEL', 'Retight control cables', 'Arrange&retight loose wires', 33),
  ('TU-1', 'electrical', 5, 'CONTROL PANEL', 'All cct brakers & switches', 'Clean&check&change if required', 34),
  ('TU-1', 'electrical', 5, 'CONTROL PANEL', 'All transformers', 'Clean by dry air', 35),
  ('TU-1', 'electrical', 5, 'CONTROL PANEL', 'All fuses', 'Clean&check&change if required', 36),
  ('TU-1', 'electrical', 5, 'CONTROL PANEL', 'All contactors', 'Clean&check&change if required', 37),
  ('TU-1', 'electrical', 5, 'CONTROL PANEL', 'All relays', 'Clean&check&change if required', 38),
  ('TU-1', 'electrical', 5, 'CONTROL PANEL', 'All electronic components', 'Clean&check&change if required', 39),
  ('TU-1', 'electrical', 5, 'CONTROL PANEL', 'D.C.drive fuses&thyrstars', 'Clean&check&change if required', 40),
  ('TU-1', 'electrical', 5, 'CONTROL PANEL', 'Drive control', 'Clean&check', 41),
  ('TU-1', 'electrical', 5, 'CONTROL PANEL', 'All terminals', 'Clean&check', 42),
  ('TU-1', 'electrical', 5, 'CONTROL PANEL', 'Panel lights', 'Clean&check&change if required', 43),
  ('TU-1', 'electrical', 5, 'CONTROL PANEL', 'Indication lamp', 'Clean&check&change if required', 44),
  ('TU-1', 'electrical', 5, 'CONTROL PANEL', 'Doors', 'Check all doors lock', 45),
  ('SC-2', 'mechanical', 1, 'PAY OFF', 'Adaptors', 'Check cond.&change if required', 1),
  ('SC-2', 'mechanical', 1, 'PAY OFF', 'Drive pin', 'Check cond.&change if required', 2),
  ('SC-2', 'mechanical', 1, 'PAY OFF', 'Gear boxes oil level', 'Check level&add if required', 3),
  ('SC-2', 'mechanical', 1, 'PAY OFF', 'Guide rollers', 'Check (bearing,shaft,surface)', 4),
  ('SC-2', 'mechanical', 1, 'PAY OFF', 'Guide pulleys', 'Check (bearing,shaft,surface)', 5),
  ('SC-2', 'mechanical', 1, 'PAY OFF', 'Open/close guide bars', 'Clean&grease', 6),
  ('SC-2', 'mechanical', 1, 'PAY OFF', 'Up/down shafts', 'Clean&grease', 7),
  ('SC-2', 'mechanical', 1, 'PAY OFF', 'Up/down nuts', 'Check cond.&grease', 8),
  ('SC-2', 'mechanical', 1, 'PAY OFF', 'Up/down guide bars', 'Clean&grease', 9),
  ('SC-2', 'mechanical', 2, 'TAPING HEAD', 'Tape brake disk', 'Check cond.&repair if required', 10),
  ('SC-2', 'mechanical', 2, 'TAPING HEAD', 'Tape brake rope', 'Check cond.&change if required', 11),
  ('SC-2', 'mechanical', 2, 'TAPING HEAD', 'Cage brake disk', 'Check cond.&repair if required', 12),
  ('SC-2', 'mechanical', 2, 'TAPING HEAD', 'Cage brake pads', 'Check cond.&change if required', 13),
  ('SC-2', 'mechanical', 2, 'TAPING HEAD', 'Guide rollers', 'Check (bearing,shaft,surface)', 14),
  ('SC-2', 'mechanical', 2, 'TAPING HEAD', 'Main bearings', 'Check cond.&grease', 15),
  ('SC-2', 'mechanical', 2, 'TAPING HEAD', 'Timing belts', 'Check cond.&change if required', 16),
  ('SC-2', 'mechanical', 2, 'TAPING HEAD', 'Air service unit', 'Lib&check cond.&change if required', 17),
  ('SC-2', 'mechanical', 2, 'TAPING HEAD', 'Air valves', 'Lib&check cond.&change if required', 18),
  ('SC-2', 'mechanical', 2, 'TAPING HEAD', 'Air hoses', 'Check cond.&change if required', 19),
  ('SC-2', 'mechanical', 2, 'TAPING HEAD', 'Air fitting', 'Check cond.&change if required', 20),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Adaptors', 'Check cond.&change if required', 21),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Drive pin', 'Check cond.&change if required', 22),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Drive holder', 'Check cond.&change if required', 23),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Balance weight', 'Check&fix removed', 24),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Bobbin brake disk', 'Check cond.&repair if required', 25),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Bobbin brake pads', 'Check cond.&change if required', 26),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Cage brake disk', 'Check cond.&repair if required', 27),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Cage brake pads', 'Check cond.&change if required', 28),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Timing belts', 'Check cond.&change if required', 29),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Open/Close pintels', 'Check cond.&clean&grease', 30),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Open/Close locks', 'Check cond.&repair if required', 31),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Guide rollers', 'Check (bearing,shaft,surface)', 32),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Main bearing', 'Check cond.&grease', 33),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Gear boxes oil level', 'Check level&add if required', 34),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Loading system', 'Check cond.&repair if required', 35),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Cage centering cylinder', 'Check cond.&change if required', 36),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Air service unit', 'Lib&check cond.&change if required', 37),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Air cylinders', 'Lib&check cond.&change if required', 38),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Air valves', 'Lib&check cond.&change if required', 39),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Air hoses', 'Check cond.&change if required', 40),
  ('SC-2', 'mechanical', 3, 'CAGE 1        (48 WIRES)', 'Air fitting', 'Check cond.&change if required', 41),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Adaptors', 'Check cond.&change if required', 42),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Drive pin', 'Check cond.&change if required', 43),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Drive holder', 'Check cond.&change if required', 44),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Balance weight', 'Check&fix removed', 45),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Bobbin brake disk', 'Check cond.&repair if required', 46),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Bobbin brake pads', 'Check cond.&change if required', 47),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Cage brake disk', 'Check cond.&repair if required', 48),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Cage brake pads', 'Check cond.&change if required', 49),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Timing belts', 'Check cond.&change if required', 50),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Open/Close pintels', 'Check cond.&clean&grease', 51),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Open/Close locks', 'Check cond.&repair if required', 52),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Guide rollers', 'Check (bearing,shaft,surface)', 53),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Main bearing', 'Check cond.&grease', 54),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Gear boxes oil level', 'Check level&add if required', 55),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Loading system', 'Check cond.&repair if required', 56),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Cage centering cylinder', 'Check cond.&change if required', 57),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Air service unit', 'Lib&check cond.&change if required', 58),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Air cylinders', 'Lib&check cond.&change if required', 59),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Air valves', 'Lib&check cond.&change if required', 60),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Air hoses', 'Check cond.&change if required', 61),
  ('SC-2', 'mechanical', 4, 'CAGE 2        (48 WIRES)', 'Air fitting', 'Check cond.&change if required', 62),
  ('SC-2', 'mechanical', 5, 'DIE HOLDER', 'Die clamp', 'Check cond.&change if required', 63),
  ('SC-2', 'mechanical', 5, 'DIE HOLDER', 'Forward/backwark', 'Grease shaft&guides', 64),
  ('SC-2', 'mechanical', 6, 'COPPER TAPING HEAD', 'Tape brake disk', 'Check cond.&repair if required', 65),
  ('SC-2', 'mechanical', 6, 'COPPER TAPING HEAD', 'Tape brake pads', 'Check cond.&change if required', 66),
  ('SC-2', 'mechanical', 6, 'COPPER TAPING HEAD', 'Cage brake disk', 'Check cond.&repair if required', 67),
  ('SC-2', 'mechanical', 6, 'COPPER TAPING HEAD', 'Cage brake pads', 'Check cond.&change if required', 68),
  ('SC-2', 'mechanical', 6, 'COPPER TAPING HEAD', 'Guide rollers', 'Check (bearing,shaft,surface)', 69),
  ('SC-2', 'mechanical', 6, 'COPPER TAPING HEAD', 'Lock nut', 'Check cond.&repair if required', 70),
  ('SC-2', 'mechanical', 6, 'COPPER TAPING HEAD', 'Main bearings', 'Check cond.&grease', 71),
  ('SC-2', 'mechanical', 6, 'COPPER TAPING HEAD', 'Timing belts', 'Check cond.&change if required', 72),
  ('SC-2', 'mechanical', 6, 'COPPER TAPING HEAD', 'Air service unit', 'Lib&check cond.&change if required', 73),
  ('SC-2', 'mechanical', 6, 'COPPER TAPING HEAD', 'Air valves', 'Lib&check cond.&change if required', 74),
  ('SC-2', 'mechanical', 6, 'COPPER TAPING HEAD', 'Air hoses', 'Check cond.&change if required', 75),
  ('SC-2', 'mechanical', 6, 'COPPER TAPING HEAD', 'Air fitting', 'Check cond.&change if required', 76),
  ('SC-2', 'mechanical', 7, 'TAPING HEAD', 'Tape brake disk', 'Check cond.&repair if required', 77),
  ('SC-2', 'mechanical', 7, 'TAPING HEAD', 'Tape brake rope', 'Check cond.&change if required', 78),
  ('SC-2', 'mechanical', 7, 'TAPING HEAD', 'Cage brake disk', 'Check cond.&repair if required', 79),
  ('SC-2', 'mechanical', 7, 'TAPING HEAD', 'Cage brake pads', 'Check cond.&change if required', 80),
  ('SC-2', 'mechanical', 7, 'TAPING HEAD', 'Guide rollers', 'Check (bearing,shaft,surface)', 81),
  ('SC-2', 'mechanical', 7, 'TAPING HEAD', 'Main bearings', 'Check cond.&grease', 82),
  ('SC-2', 'mechanical', 7, 'TAPING HEAD', 'Timing belts', 'Check cond.&change if required', 83),
  ('SC-2', 'mechanical', 7, 'TAPING HEAD', 'Air service unit', 'Lib&check cond.&change if required', 84),
  ('SC-2', 'mechanical', 7, 'TAPING HEAD', 'Air valves', 'Lib&check cond.&change if required', 85),
  ('SC-2', 'mechanical', 7, 'TAPING HEAD', 'Air hoses', 'Check cond.&change if required', 86),
  ('SC-2', 'mechanical', 7, 'TAPING HEAD', 'Air fitting', 'Check cond.&change if required', 87),
  ('SC-2', 'mechanical', 8, 'TENSION CATERPILLAR', 'Gear boxes oil level', 'Check oil level&add if required', 88),
  ('SC-2', 'mechanical', 8, 'TENSION CATERPILLAR', 'Belt guide rollers', 'Check cond.&change if required', 89),
  ('SC-2', 'mechanical', 8, 'TENSION CATERPILLAR', 'Drive belts', 'Check cond.&change if required', 90),
  ('SC-2', 'mechanical', 8, 'TENSION CATERPILLAR', 'Tension cylinder', 'Check cond.&change if required', 91),
  ('SC-2', 'mechanical', 8, 'TENSION CATERPILLAR', 'Tension pulleys', 'Check cond.&bearings', 92),
  ('SC-2', 'mechanical', 8, 'TENSION CATERPILLAR', 'Drive pulleys', 'Check cond.&key way', 93),
  ('SC-2', 'mechanical', 8, 'TENSION CATERPILLAR', 'Pressing cylinders', 'Check cond.&change if required', 94),
  ('SC-2', 'mechanical', 8, 'TENSION CATERPILLAR', 'Pressing rollers', 'Check bearing stuck&change if required', 95),
  ('SC-2', 'mechanical', 8, 'TENSION CATERPILLAR', 'Guide rollers', 'Check (bearing,shaft,surface)', 96),
  ('SC-2', 'mechanical', 8, 'TENSION CATERPILLAR', 'Air service unit', 'Lib&check cond.&change if required', 97),
  ('SC-2', 'mechanical', 8, 'TENSION CATERPILLAR', 'Air valves', 'Lib&check cond.&change if required', 98),
  ('SC-2', 'mechanical', 8, 'TENSION CATERPILLAR', 'Air hoses', 'Check cond.&change if required', 99),
  ('SC-2', 'mechanical', 8, 'TENSION CATERPILLAR', 'Air fitting', 'Check cond.&change if required', 100),
  ('SC-2', 'mechanical', 9, 'COUNTER METER', 'Pulleys', 'Check (bearing,shaft,surface)', 101),
  ('SC-2', 'mechanical', 9, 'COUNTER METER', 'Guide rollers', 'Check (bearing,shaft,surface)', 102),
  ('SC-2', 'mechanical', 9, 'COUNTER METER', 'Flat belt', 'Check cond.&change if required', 103),
  ('SC-2', 'mechanical', 10, 'TAKE UP', 'Adaptors', 'Check cond.&change if required', 104),
  ('SC-2', 'mechanical', 10, 'TAKE UP', 'Drive pin', 'Check cond.&change if required', 105),
  ('SC-2', 'mechanical', 10, 'TAKE UP', 'Gear boxes oil level', 'Check oil level&add if required', 106),
  ('SC-2', 'mechanical', 10, 'TAKE UP', 'Open/close guide bars', 'Clean&grease', 107),
  ('SC-2', 'mechanical', 10, 'TAKE UP', 'Up/down shafts', 'Clean&grease', 108),
  ('SC-2', 'mechanical', 10, 'TAKE UP', 'Up/down nuts', 'Check cond.&grease', 109),
  ('SC-2', 'mechanical', 10, 'TAKE UP', 'Up/down guide bars', 'Clean&grease', 110),
  ('SC-2', 'mechanical', 10, 'TAKE UP', 'Traverse wheels', 'Check cond.&repair if required', 111),
  ('SC-2', 'mechanical', 10, 'TAKE UP', 'Traverse guide bars', 'Clean&grease', 112),
  ('SC-2', 'mechanical', 10, 'TAKE UP', 'Guide rollers', 'Check (bearing,shaft,surface)', 113),
  ('SC-2', 'electrical', 1, 'PAY OFF', 'Winding motor', 'Check cond.&clean by dry air', 1),
  ('SC-2', 'electrical', 1, 'PAY OFF', 'Open/close motor', 'Check cond.&clean by dry air', 2),
  ('SC-2', 'electrical', 1, 'PAY OFF', 'Up/down motors', 'Check cond.&clean by dry air', 3),
  ('SC-2', 'electrical', 1, 'PAY OFF', 'Limit switches', 'Check cond.&change if required', 4),
  ('SC-2', 'electrical', 1, 'PAY OFF', 'Cooling fan', 'Check cond.&clean by dry air', 5),
  ('SC-2', 'electrical', 1, 'PAY OFF', 'Encoder', 'Check cond.&signal', 6),
  ('SC-2', 'electrical', 1, 'PAY OFF', 'Cable tray', 'Check cond.&repair if required', 7),
  ('SC-2', 'electrical', 1, 'PAY OFF', 'Terminal boxes', 'Clean by dry air', 8),
  ('SC-2', 'electrical', 2, 'TAPING HEAD', 'Motor', 'Check cond.&clean by dry air', 9),
  ('SC-2', 'electrical', 2, 'TAPING HEAD', 'Cooling fan', 'Check cond.&clean by dry air', 10),
  ('SC-2', 'electrical', 2, 'TAPING HEAD', 'Air pressure switch', 'Check cond.&change if required', 11),
  ('SC-2', 'electrical', 2, 'TAPING HEAD', 'Encoder', 'Check cond.&signal', 12),
  ('SC-2', 'electrical', 2, 'TAPING HEAD', 'Sensors', 'Check cond.&change if required', 13),
  ('SC-2', 'electrical', 2, 'TAPING HEAD', 'Door switch', 'Check cond.&change if required', 14),
  ('SC-2', 'electrical', 2, 'TAPING HEAD', 'Carbon brushes', 'Check cond.&change if required', 15),
  ('SC-2', 'electrical', 2, 'TAPING HEAD', 'Slip rings', 'Check cond.&clean by dry air', 16),
  ('SC-2', 'electrical', 2, 'TAPING HEAD', 'Terminal boxes', 'Clean by dry air', 17),
  ('SC-2', 'electrical', 3, 'CAGE 1          (48 WIRES)', 'Main motor', 'Check cond.&repair  if required', 18),
  ('SC-2', 'electrical', 3, 'CAGE 1          (48 WIRES)', 'Jog motor', 'Check cond.&clean by dry air', 19),
  ('SC-2', 'electrical', 3, 'CAGE 1          (48 WIRES)', 'Cooling blowers', 'Check cond.&clean by dry air', 20),
  ('SC-2', 'electrical', 3, 'CAGE 1          (48 WIRES)', 'Cooling fan filter', 'Change', 21),
  ('SC-2', 'electrical', 3, 'CAGE 1          (48 WIRES)', 'Encoder', 'Check cond.&signal', 22),
  ('SC-2', 'electrical', 3, 'CAGE 1          (48 WIRES)', 'Clyinders sensors', 'Check cond.&change if required', 23),
  ('SC-2', 'electrical', 3, 'CAGE 1          (48 WIRES)', 'Sensors', 'Check cond.&change if required', 24),
  ('SC-2', 'electrical', 3, 'CAGE 1          (48 WIRES)', 'Limit switches', 'Check cond.&change if required', 25),
  ('SC-2', 'electrical', 3, 'CAGE 1          (48 WIRES)', 'Carbon brushes', 'Check cond.&change if required', 26),
  ('SC-2', 'electrical', 3, 'CAGE 1          (48 WIRES)', 'Carbon brushes holders', 'Check cond.&repair  if required', 27),
  ('SC-2', 'electrical', 3, 'CAGE 1          (48 WIRES)', 'Slip rings', 'Check cond.&clean by dry air', 28),
  ('SC-2', 'electrical', 3, 'CAGE 1          (48 WIRES)', 'Wire break', 'Check cond.&repair  if required', 29),
  ('SC-2', 'electrical', 3, 'CAGE 1          (48 WIRES)', 'Terminal boxes', 'Clean by dry air', 30),
  ('SC-2', 'electrical', 4, 'CAGE 2          (48 WIRES)', 'Main motor', 'Check cond.&repair  if required', 31),
  ('SC-2', 'electrical', 4, 'CAGE 2          (48 WIRES)', 'Jog motor', 'Check cond.&clean by dry air', 32),
  ('SC-2', 'electrical', 4, 'CAGE 2          (48 WIRES)', 'Cooling blowers', 'Check cond.&clean by dry air', 33),
  ('SC-2', 'electrical', 4, 'CAGE 2          (48 WIRES)', 'Cooling fan filter', 'Change', 34),
  ('SC-2', 'electrical', 4, 'CAGE 2          (48 WIRES)', 'Encoder', 'Check cond.&signal', 35),
  ('SC-2', 'electrical', 4, 'CAGE 2          (48 WIRES)', 'Clyinders sensors', 'Check cond.&change if required', 36),
  ('SC-2', 'electrical', 4, 'CAGE 2          (48 WIRES)', 'Sensors', 'Check cond.&change if required', 37),
  ('SC-2', 'electrical', 4, 'CAGE 2          (48 WIRES)', 'Limit switches', 'Check cond.&change if required', 38),
  ('SC-2', 'electrical', 4, 'CAGE 2          (48 WIRES)', 'Carbon brushes', 'Check cond.&change if required', 39),
  ('SC-2', 'electrical', 4, 'CAGE 2          (48 WIRES)', 'Carbon brushes holders', 'Check cond.&repair  if required', 40),
  ('SC-2', 'electrical', 4, 'CAGE 2          (48 WIRES)', 'Slip rings', 'Check cond.&clean by dry air', 41),
  ('SC-2', 'electrical', 4, 'CAGE 2          (48 WIRES)', 'Wire break', 'Check cond.&repair  if required', 42),
  ('SC-2', 'electrical', 4, 'CAGE 2          (48 WIRES)', 'Terminal boxes', 'Clean by dry air', 43),
  ('SC-2', 'electrical', 5, 'COPPER TAPE', 'Motor', 'Check cond.&clean by dry air', 44),
  ('SC-2', 'electrical', 5, 'COPPER TAPE', 'Cooling blower', 'Check cond.&clean by dry air', 45),
  ('SC-2', 'electrical', 5, 'COPPER TAPE', 'Air pressure switch', 'Check cond.&change if required', 46),
  ('SC-2', 'electrical', 5, 'COPPER TAPE', 'Encoder', 'Check cond.&signal', 47),
  ('SC-2', 'electrical', 5, 'COPPER TAPE', 'Sensors', 'Check cond.&change if required', 48),
  ('SC-2', 'electrical', 5, 'COPPER TAPE', 'Door switch', 'Check cond.&change if required', 49),
  ('SC-2', 'electrical', 5, 'COPPER TAPE', 'Carbon brushes', 'Check cond.&change if required', 50),
  ('SC-2', 'electrical', 5, 'COPPER TAPE', 'Slip rings', 'Check cond.&clean by dry air', 51),
  ('SC-2', 'electrical', 5, 'COPPER TAPE', 'Terminal boxes', 'Clean by dry air', 52),
  ('SC-2', 'electrical', 6, 'TAPING HEAD', 'Motor', 'Check cond.&clean by dry air', 53),
  ('SC-2', 'electrical', 6, 'TAPING HEAD', 'Cooling blower', 'Check cond.&clean by dry air', 54),
  ('SC-2', 'electrical', 6, 'TAPING HEAD', 'Air pressure switch', 'Check cond.&change if required', 55),
  ('SC-2', 'electrical', 6, 'TAPING HEAD', 'Encoder', 'Check cond.&signal', 56),
  ('SC-2', 'electrical', 6, 'TAPING HEAD', 'Sensors', 'Check cond.&change if required', 57),
  ('SC-2', 'electrical', 6, 'TAPING HEAD', 'Door switch', 'Check cond.&change if required', 58),
  ('SC-2', 'electrical', 6, 'TAPING HEAD', 'Carbon brushes', 'Check cond.&change if required', 59),
  ('SC-2', 'electrical', 6, 'TAPING HEAD', 'Slip rings', 'Check cond.&clean by dry air', 60),
  ('SC-2', 'electrical', 6, 'TAPING HEAD', 'Terminal boxes', 'Clean by dry air', 61),
  ('SC-2', 'electrical', 7, 'TENSION CATERPILLAR', 'Drive motors', 'Check cond.&clean by dry air', 62),
  ('SC-2', 'electrical', 7, 'TENSION CATERPILLAR', 'Cooling fan', 'Check cond.&clean by dry air', 63),
  ('SC-2', 'electrical', 7, 'TENSION CATERPILLAR', 'Encoder', 'Check cond.&signal', 64),
  ('SC-2', 'electrical', 7, 'TENSION CATERPILLAR', 'Air pressure switch', 'Check cond.&change if required', 65),
  ('SC-2', 'electrical', 7, 'TENSION CATERPILLAR', 'Terminal boxes', 'Clean by dry air', 66),
  ('SC-2', 'electrical', 8, 'COUNTER METER', 'Encoder', 'Check cond.&signal', 67),
  ('SC-2', 'electrical', 8, 'COUNTER METER', 'Sensors', 'Check cond.&signal', 68),
  ('SC-2', 'electrical', 9, 'TAKE UP', 'Open/close motors', 'Check cond.&clean by dry air', 69),
  ('SC-2', 'electrical', 9, 'TAKE UP', 'Open/close limit switch', 'Check cond.&change if required', 70),
  ('SC-2', 'electrical', 9, 'TAKE UP', 'Up/down motors', 'Check cond.&clean by dry air', 71),
  ('SC-2', 'electrical', 9, 'TAKE UP', 'Up/down limit switches', 'Check cond.&change if required', 72),
  ('SC-2', 'electrical', 9, 'TAKE UP', 'Traverse motor', 'Check cond.&clean by dry air', 73),
  ('SC-2', 'electrical', 9, 'TAKE UP', 'Winding motor', 'Check cond.&clean by dry air', 74),
  ('SC-2', 'electrical', 9, 'TAKE UP', 'Cooling fan', 'Check cond.&clean by dry air', 75),
  ('SC-2', 'electrical', 9, 'TAKE UP', 'Encoder', 'Check cond.&signal', 76),
  ('SC-2', 'electrical', 9, 'TAKE UP', 'Sensors', 'Check cond.&change if required', 77),
  ('SC-2', 'electrical', 9, 'TAKE UP', 'Cable tray', 'Check cond.&repair if required', 78),
  ('SC-2', 'electrical', 9, 'TAKE UP', 'Terminal boxes', 'Clean by dry air', 79),
  ('SC-2', 'electrical', 10, 'CONTROL PANEL', 'Air condition', 'Clean by dry air', 80),
  ('SC-2', 'electrical', 10, 'CONTROL PANEL', 'Retight power cables', 'Retight cables', 81),
  ('SC-2', 'electrical', 10, 'CONTROL PANEL', 'Retight control cables', 'Arrange&retight loose wires', 82),
  ('SC-2', 'electrical', 10, 'CONTROL PANEL', 'All cct brakers & switches', 'Clean&check&change if required', 83),
  ('SC-2', 'electrical', 10, 'CONTROL PANEL', 'All transformers', 'Clean by dry air', 84),
  ('SC-2', 'electrical', 10, 'CONTROL PANEL', 'All fuses', 'Clean&check&change if required', 85),
  ('SC-2', 'electrical', 10, 'CONTROL PANEL', 'All contactors', 'Clean&check&change if required', 86),
  ('SC-2', 'electrical', 10, 'CONTROL PANEL', 'All relays', 'Clean&check&change if required', 87),
  ('SC-2', 'electrical', 10, 'CONTROL PANEL', 'All electronic components', 'Clean&check&change if required', 88),
  ('SC-2', 'electrical', 10, 'CONTROL PANEL', 'D.C.drive fuses&thyrstars', 'Clean&check&change if required', 89),
  ('SC-2', 'electrical', 10, 'CONTROL PANEL', 'Drive control', 'Clean&check', 90),
  ('SC-2', 'electrical', 10, 'CONTROL PANEL', 'All terminals', 'Clean&check', 91),
  ('SC-2', 'electrical', 10, 'CONTROL PANEL', 'Indication lamp', 'Clean&check&change if required', 92),
  ('SC-2', 'electrical', 10, 'CONTROL PANEL', 'Doors', 'Check all doors lock', 93);
